CREATE TABLE Users(
username VARCHAR(15),
password VARCHAR(15),
Firstname VARCHAR(20) NOT NULL,
Lastname VARCHAR(20) NOT NULL,
DOB DATE NOT NULL,
PhoneNumber VARCHAR(10),
AltPhone VARCHAR(10),
Email VARCHAR(30) NOT NULL,
Age INTEGER,
Gender VARCHAR(10),
EmergFirstName VARCHAR(15),
EmergLastName VARCHAR(15),
Relationship VARCHAR(15),
EmergNumber VARCHAR(10),
PharmName VARCHAR(15),
PharmNum VARCHAR(10),
DoctorName VARCHAR(15),
DoctorNum VARCHAR(10),
Height INTEGER,
Weight INTEGER,
streetAddress VARCHAR(30),
zip INTEGER,
state VARCHAR(15),
city VARCHAR (25),
PRIMARY KEY(username),
UNIQUE(PhoneNumber),
UNIQUE(AltPhone),
UNIQUE(Email));

CREATE TABLE Doctors(
speciality VARCHAR(25),
firstName VARCHAR(15),
lastName VARCHAR(15),
PRIMARY KEY(firstName,lastName)
);

INSERT INTO Doctors(speciality,firstName,lastName)
VALUES
('Cardiology','John', 'Smith'),
('Cardiology','Julie', 'Trent'),
('Cardiology','Tina', 'Smores'),
('Cardiology','Flora', 'Dora'),
('Cardiology','Brian', 'Jerry'),
('Dermatology','Larry', 'Mart'),
('Dermatology','Mike', 'Menlo'),
('Dermatology','Gina', 'Park'),
('Dermatology','Laura', 'River'),
('Gastroenterology','Fiona', 'Mint'),
('Gastroenterology','Charlie', 'Silver'),
('Gastroenterology','Todd', 'Gold'),
('Gastroenterology','Walter', 'Black'),
('Gynecology','Jesse', 'Red'),
('Gynecology','Skyler', 'Blue'),
('Gynecology','Harry', 'Basil'),
('Internal Medicine','John', 'Pepper'),
('Internal Medicine','Jerry', 'White'),
('Internal Medicine','George', 'Garley'),
('Orthopedics','Carly', 'Smithson'),
('Orthopedics','Gerald', 'Tare'),
('Orthopedics','Ron', 'Forte'),
('Pediatrics','Bill', 'Sante'),
('Pediatrics','Gloria', 'Gem'),
('Pediatrics','Miley', 'Cyro'),
('Pulmonology','Liam', 'Shape'),
('Pulmonology','Nial', 'Tarpe'),
('Pulmonology','Louis', 'Fisher'),
('Radiology','Jared', 'Home'),
('Radiology','Rya', 'Gupta'),
('Radiology','Amy', 'Diaz'),
('Urology','Mario', 'Sanchez'),
('Urology','Hank', 'Gera'),
('Urology','Vincent', 'Lorey'),
('Urology','Jake', 'Diner');


CREATE TABLE Makes_Appt (
username VARCHAR(15),
firstNameDoc VARCHAR(15),
lastNameDoc VARCHAR(15),
speciality VARCHAR(25),
dateApt DATE,
PRIMARY KEY(username,lastNameDoc,speciality,dateApt),
FOREIGN KEY(username) REFERENCES Users,
FOREIGN KEY(lastNameDoc, speciality) REFERENCES Doctors);
